language: java
sudo: required
dist: trust"
group: edge
jdk:
  - oraclejdk8
  - oraclejdk9

script:
      - git clone https://github.com/retronym/java9-rt-export
      - cd java9-rt-export/
      - git checkout 1019a2873d057dd7214f4135e84283695728395d
      - jdk_switcher use oraclejdk8
      - sbt package
      - jdk_switcher use oraclejdk9
      - java -version
      - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
      - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
      - cd ..
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/9ade5fa54914ca8aded44105bf4b9a60966f3ccd/sbt && chmod +x ./sbt
      - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION testSequential
      addons:
        apt:
          packages:
          - oracle-java9-installer

os: linux

