language: java
sudo: required
group: edge
jdk:
 - oraclejdk8
 - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/Java9

